/* tslint:disable */
/* eslint-disable */
/**
 * The Jira Cloud platform REST API
 * Jira Cloud platform REST API documentation
 *
 * The version of the OpenAPI document: 1001.0.0-SNAPSHOT-21695d0ffb3094632d6272be3e6600848f05a23b
 * Contact: ecosystem@atlassian.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  AvailableDashboardGadgetsResponse,
  BulkEditShareableEntityRequest,
  BulkEditShareableEntityResponse,
  Dashboard,
  DashboardDetails,
  DashboardGadget,
  DashboardGadgetResponse,
  DashboardGadgetSettings,
  DashboardGadgetUpdateRequest,
  EntityProperty,
  ErrorCollection,
  PageBeanDashboard,
  PageOfDashboards,
  PropertyKeys,
} from '../models/index';

export interface AddGadgetRequest {
    dashboardId: number;
    dashboardGadgetSettings: DashboardGadgetSettings;
}

export interface BulkEditDashboardsRequest {
    bulkEditShareableEntityRequest: BulkEditShareableEntityRequest;
}

export interface CopyDashboardRequest {
    id: string;
    dashboardDetails: DashboardDetails;
    extendAdminPermissions?: boolean;
}

export interface CreateDashboardRequest {
    dashboardDetails: DashboardDetails;
    extendAdminPermissions?: boolean;
}

export interface DeleteDashboardRequest {
    id: string;
}

export interface DeleteDashboardItemPropertyRequest {
    dashboardId: string;
    itemId: string;
    propertyKey: string;
}

export interface GetAllDashboardsRequest {
    filter?: GetAllDashboardsFilterEnum;
    startAt?: number;
    maxResults?: number;
}

export interface GetAllGadgetsRequest {
    dashboardId: number;
    moduleKey?: Array<string>;
    uri?: Array<string>;
    gadgetId?: Array<number>;
}

export interface GetDashboardRequest {
    id: string;
}

export interface GetDashboardItemPropertyRequest {
    dashboardId: string;
    itemId: string;
    propertyKey: string;
}

export interface GetDashboardItemPropertyKeysRequest {
    dashboardId: string;
    itemId: string;
}

export interface GetDashboardsPaginatedRequest {
    dashboardName?: string;
    accountId?: string;
    owner?: string;
    groupname?: string;
    groupId?: string;
    projectId?: number;
    orderBy?: GetDashboardsPaginatedOrderByEnum;
    startAt?: number;
    maxResults?: number;
    status?: GetDashboardsPaginatedStatusEnum;
    expand?: string;
}

export interface RemoveGadgetRequest {
    dashboardId: number;
    gadgetId: number;
}

export interface SetDashboardItemPropertyRequest {
    dashboardId: string;
    itemId: string;
    propertyKey: string;
    body: any | null;
}

export interface UpdateDashboardRequest {
    id: string;
    dashboardDetails: DashboardDetails;
    extendAdminPermissions?: boolean;
}

export interface UpdateGadgetRequest {
    dashboardId: number;
    gadgetId: number;
    dashboardGadgetUpdateRequest: DashboardGadgetUpdateRequest;
}

/**
 * 
 */
export class DashboardsApi extends runtime.BaseAPI {

    /**
     * Creates request options for addGadget without sending the request
     */
    async addGadgetRequestOpts(requestParameters: AddGadgetRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['dashboardId'] == null) {
            throw new runtime.RequiredError(
                'dashboardId',
                'Required parameter "dashboardId" was null or undefined when calling addGadget().'
            );
        }

        if (requestParameters['dashboardGadgetSettings'] == null) {
            throw new runtime.RequiredError(
                'dashboardGadgetSettings',
                'Required parameter "dashboardGadgetSettings" was null or undefined when calling addGadget().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("OAuth2", ["write:jira-work", "read:jira-work"]);
        }

        if (this.configuration && (this.configuration.username !== undefined || this.configuration.password !== undefined)) {
            headerParameters["Authorization"] = "Basic " + btoa(this.configuration.username + ":" + this.configuration.password);
        }

        let urlPath = `/rest/api/3/dashboard/{dashboardId}/gadget`;
        urlPath = urlPath.replace(`{${"dashboardId"}}`, encodeURIComponent(String(requestParameters['dashboardId'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters['dashboardGadgetSettings'],
        };
    }

    /**
     * Adds a gadget to a dashboard.  **[Permissions](#permissions) required:** None.
     * Add gadget to dashboard
     */
    async addGadgetRaw(requestParameters: AddGadgetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<DashboardGadget>> {
        const requestOptions = await this.addGadgetRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response);
    }

    /**
     * Adds a gadget to a dashboard.  **[Permissions](#permissions) required:** None.
     * Add gadget to dashboard
     */
    async addGadget(requestParameters: AddGadgetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<DashboardGadget> {
        const response = await this.addGadgetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for bulkEditDashboards without sending the request
     */
    async bulkEditDashboardsRequestOpts(requestParameters: BulkEditDashboardsRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['bulkEditShareableEntityRequest'] == null) {
            throw new runtime.RequiredError(
                'bulkEditShareableEntityRequest',
                'Required parameter "bulkEditShareableEntityRequest" was null or undefined when calling bulkEditDashboards().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("OAuth2", ["write:jira-work"]);
        }

        if (this.configuration && (this.configuration.username !== undefined || this.configuration.password !== undefined)) {
            headerParameters["Authorization"] = "Basic " + btoa(this.configuration.username + ":" + this.configuration.password);
        }

        let urlPath = `/rest/api/3/dashboard/bulk/edit`;

        return {
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters['bulkEditShareableEntityRequest'],
        };
    }

    /**
     * Bulk edit dashboards. Maximum number of dashboards to be edited at the same time is 100.  **[Permissions](#permissions) required:** None  The dashboards to be updated must be owned by the user, or the user must be an administrator.
     * Bulk edit dashboards
     */
    async bulkEditDashboardsRaw(requestParameters: BulkEditDashboardsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<BulkEditShareableEntityResponse>> {
        const requestOptions = await this.bulkEditDashboardsRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response);
    }

    /**
     * Bulk edit dashboards. Maximum number of dashboards to be edited at the same time is 100.  **[Permissions](#permissions) required:** None  The dashboards to be updated must be owned by the user, or the user must be an administrator.
     * Bulk edit dashboards
     */
    async bulkEditDashboards(requestParameters: BulkEditDashboardsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<BulkEditShareableEntityResponse> {
        const response = await this.bulkEditDashboardsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for copyDashboard without sending the request
     */
    async copyDashboardRequestOpts(requestParameters: CopyDashboardRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling copyDashboard().'
            );
        }

        if (requestParameters['dashboardDetails'] == null) {
            throw new runtime.RequiredError(
                'dashboardDetails',
                'Required parameter "dashboardDetails" was null or undefined when calling copyDashboard().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['extendAdminPermissions'] != null) {
            queryParameters['extendAdminPermissions'] = requestParameters['extendAdminPermissions'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("OAuth2", ["write:jira-work"]);
        }

        if (this.configuration && (this.configuration.username !== undefined || this.configuration.password !== undefined)) {
            headerParameters["Authorization"] = "Basic " + btoa(this.configuration.username + ":" + this.configuration.password);
        }

        let urlPath = `/rest/api/3/dashboard/{id}/copy`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters['dashboardDetails'],
        };
    }

    /**
     * Copies a dashboard. Any values provided in the `dashboard` parameter replace those in the copied dashboard.  **[Permissions](#permissions) required:** None  The dashboard to be copied must be owned by or shared with the user.
     * Copy dashboard
     */
    async copyDashboardRaw(requestParameters: CopyDashboardRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Dashboard>> {
        const requestOptions = await this.copyDashboardRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response);
    }

    /**
     * Copies a dashboard. Any values provided in the `dashboard` parameter replace those in the copied dashboard.  **[Permissions](#permissions) required:** None  The dashboard to be copied must be owned by or shared with the user.
     * Copy dashboard
     */
    async copyDashboard(requestParameters: CopyDashboardRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Dashboard> {
        const response = await this.copyDashboardRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for createDashboard without sending the request
     */
    async createDashboardRequestOpts(requestParameters: CreateDashboardRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['dashboardDetails'] == null) {
            throw new runtime.RequiredError(
                'dashboardDetails',
                'Required parameter "dashboardDetails" was null or undefined when calling createDashboard().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['extendAdminPermissions'] != null) {
            queryParameters['extendAdminPermissions'] = requestParameters['extendAdminPermissions'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("OAuth2", ["write:jira-work"]);
        }

        if (this.configuration && (this.configuration.username !== undefined || this.configuration.password !== undefined)) {
            headerParameters["Authorization"] = "Basic " + btoa(this.configuration.username + ":" + this.configuration.password);
        }

        let urlPath = `/rest/api/3/dashboard`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters['dashboardDetails'],
        };
    }

    /**
     * Creates a dashboard.  **[Permissions](#permissions) required:** None.
     * Create dashboard
     */
    async createDashboardRaw(requestParameters: CreateDashboardRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Dashboard>> {
        const requestOptions = await this.createDashboardRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response);
    }

    /**
     * Creates a dashboard.  **[Permissions](#permissions) required:** None.
     * Create dashboard
     */
    async createDashboard(requestParameters: CreateDashboardRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Dashboard> {
        const response = await this.createDashboardRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for deleteDashboard without sending the request
     */
    async deleteDashboardRequestOpts(requestParameters: DeleteDashboardRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling deleteDashboard().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("OAuth2", ["write:jira-work"]);
        }

        if (this.configuration && (this.configuration.username !== undefined || this.configuration.password !== undefined)) {
            headerParameters["Authorization"] = "Basic " + btoa(this.configuration.username + ":" + this.configuration.password);
        }

        let urlPath = `/rest/api/3/dashboard/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Deletes a dashboard.  **[Permissions](#permissions) required:** None  The dashboard to be deleted must be owned by the user.
     * Delete dashboard
     */
    async deleteDashboardRaw(requestParameters: DeleteDashboardRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.deleteDashboardRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Deletes a dashboard.  **[Permissions](#permissions) required:** None  The dashboard to be deleted must be owned by the user.
     * Delete dashboard
     */
    async deleteDashboard(requestParameters: DeleteDashboardRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.deleteDashboardRaw(requestParameters, initOverrides);
    }

    /**
     * Creates request options for deleteDashboardItemProperty without sending the request
     */
    async deleteDashboardItemPropertyRequestOpts(requestParameters: DeleteDashboardItemPropertyRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['dashboardId'] == null) {
            throw new runtime.RequiredError(
                'dashboardId',
                'Required parameter "dashboardId" was null or undefined when calling deleteDashboardItemProperty().'
            );
        }

        if (requestParameters['itemId'] == null) {
            throw new runtime.RequiredError(
                'itemId',
                'Required parameter "itemId" was null or undefined when calling deleteDashboardItemProperty().'
            );
        }

        if (requestParameters['propertyKey'] == null) {
            throw new runtime.RequiredError(
                'propertyKey',
                'Required parameter "propertyKey" was null or undefined when calling deleteDashboardItemProperty().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("OAuth2", ["write:jira-work"]);
        }

        if (this.configuration && (this.configuration.username !== undefined || this.configuration.password !== undefined)) {
            headerParameters["Authorization"] = "Basic " + btoa(this.configuration.username + ":" + this.configuration.password);
        }

        let urlPath = `/rest/api/3/dashboard/{dashboardId}/items/{itemId}/properties/{propertyKey}`;
        urlPath = urlPath.replace(`{${"dashboardId"}}`, encodeURIComponent(String(requestParameters['dashboardId'])));
        urlPath = urlPath.replace(`{${"itemId"}}`, encodeURIComponent(String(requestParameters['itemId'])));
        urlPath = urlPath.replace(`{${"propertyKey"}}`, encodeURIComponent(String(requestParameters['propertyKey'])));

        return {
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Deletes a dashboard item property.  This operation can be accessed anonymously.  **[Permissions](#permissions) required:** The user must have edit permission of the dashboard.
     * Delete dashboard item property
     */
    async deleteDashboardItemPropertyRaw(requestParameters: DeleteDashboardItemPropertyRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>> {
        const requestOptions = await this.deleteDashboardItemPropertyRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<any>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Deletes a dashboard item property.  This operation can be accessed anonymously.  **[Permissions](#permissions) required:** The user must have edit permission of the dashboard.
     * Delete dashboard item property
     */
    async deleteDashboardItemProperty(requestParameters: DeleteDashboardItemPropertyRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any> {
        const response = await this.deleteDashboardItemPropertyRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getAllAvailableDashboardGadgets without sending the request
     */
    async getAllAvailableDashboardGadgetsRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("OAuth2", ["read:jira-work"]);
        }

        if (this.configuration && (this.configuration.username !== undefined || this.configuration.password !== undefined)) {
            headerParameters["Authorization"] = "Basic " + btoa(this.configuration.username + ":" + this.configuration.password);
        }

        let urlPath = `/rest/api/3/dashboard/gadgets`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Gets a list of all available gadgets that can be added to all dashboards.  **[Permissions](#permissions) required:** None.
     * Get available gadgets
     */
    async getAllAvailableDashboardGadgetsRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AvailableDashboardGadgetsResponse>> {
        const requestOptions = await this.getAllAvailableDashboardGadgetsRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response);
    }

    /**
     * Gets a list of all available gadgets that can be added to all dashboards.  **[Permissions](#permissions) required:** None.
     * Get available gadgets
     */
    async getAllAvailableDashboardGadgets(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AvailableDashboardGadgetsResponse> {
        const response = await this.getAllAvailableDashboardGadgetsRaw(initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getAllDashboards without sending the request
     */
    async getAllDashboardsRequestOpts(requestParameters: GetAllDashboardsRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        if (requestParameters['filter'] != null) {
            queryParameters['filter'] = requestParameters['filter'];
        }

        if (requestParameters['startAt'] != null) {
            queryParameters['startAt'] = requestParameters['startAt'];
        }

        if (requestParameters['maxResults'] != null) {
            queryParameters['maxResults'] = requestParameters['maxResults'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("OAuth2", ["read:jira-work"]);
        }

        if (this.configuration && (this.configuration.username !== undefined || this.configuration.password !== undefined)) {
            headerParameters["Authorization"] = "Basic " + btoa(this.configuration.username + ":" + this.configuration.password);
        }

        let urlPath = `/rest/api/3/dashboard`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Returns a list of dashboards owned by or shared with the user. The list may be filtered to include only favorite or owned dashboards.  This operation can be accessed anonymously.  **[Permissions](#permissions) required:** None.
     * Get all dashboards
     */
    async getAllDashboardsRaw(requestParameters: GetAllDashboardsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PageOfDashboards>> {
        const requestOptions = await this.getAllDashboardsRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response);
    }

    /**
     * Returns a list of dashboards owned by or shared with the user. The list may be filtered to include only favorite or owned dashboards.  This operation can be accessed anonymously.  **[Permissions](#permissions) required:** None.
     * Get all dashboards
     */
    async getAllDashboards(requestParameters: GetAllDashboardsRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PageOfDashboards> {
        const response = await this.getAllDashboardsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getAllGadgets without sending the request
     */
    async getAllGadgetsRequestOpts(requestParameters: GetAllGadgetsRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['dashboardId'] == null) {
            throw new runtime.RequiredError(
                'dashboardId',
                'Required parameter "dashboardId" was null or undefined when calling getAllGadgets().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['moduleKey'] != null) {
            queryParameters['moduleKey'] = requestParameters['moduleKey'];
        }

        if (requestParameters['uri'] != null) {
            queryParameters['uri'] = requestParameters['uri'];
        }

        if (requestParameters['gadgetId'] != null) {
            queryParameters['gadgetId'] = requestParameters['gadgetId'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("OAuth2", ["read:jira-work"]);
        }

        if (this.configuration && (this.configuration.username !== undefined || this.configuration.password !== undefined)) {
            headerParameters["Authorization"] = "Basic " + btoa(this.configuration.username + ":" + this.configuration.password);
        }

        let urlPath = `/rest/api/3/dashboard/{dashboardId}/gadget`;
        urlPath = urlPath.replace(`{${"dashboardId"}}`, encodeURIComponent(String(requestParameters['dashboardId'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Returns a list of dashboard gadgets on a dashboard.  This operation returns:   *  Gadgets from a list of IDs, when `id` is set.  *  Gadgets with a module key, when `moduleKey` is set.  *  Gadgets from a list of URIs, when `uri` is set.  *  All gadgets, when no other parameters are set.  This operation can be accessed anonymously.  **[Permissions](#permissions) required:** None.
     * Get gadgets
     */
    async getAllGadgetsRaw(requestParameters: GetAllGadgetsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<DashboardGadgetResponse>> {
        const requestOptions = await this.getAllGadgetsRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response);
    }

    /**
     * Returns a list of dashboard gadgets on a dashboard.  This operation returns:   *  Gadgets from a list of IDs, when `id` is set.  *  Gadgets with a module key, when `moduleKey` is set.  *  Gadgets from a list of URIs, when `uri` is set.  *  All gadgets, when no other parameters are set.  This operation can be accessed anonymously.  **[Permissions](#permissions) required:** None.
     * Get gadgets
     */
    async getAllGadgets(requestParameters: GetAllGadgetsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<DashboardGadgetResponse> {
        const response = await this.getAllGadgetsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getDashboard without sending the request
     */
    async getDashboardRequestOpts(requestParameters: GetDashboardRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling getDashboard().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("OAuth2", ["read:jira-work"]);
        }

        if (this.configuration && (this.configuration.username !== undefined || this.configuration.password !== undefined)) {
            headerParameters["Authorization"] = "Basic " + btoa(this.configuration.username + ":" + this.configuration.password);
        }

        let urlPath = `/rest/api/3/dashboard/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Returns a dashboard.  This operation can be accessed anonymously.  **[Permissions](#permissions) required:** None.  However, to get a dashboard, the dashboard must be shared with the user or the user must own it. Note, users with the *Administer Jira* [global permission](https://confluence.atlassian.com/x/x4dKLg) are considered owners of the System dashboard. The System dashboard is considered to be shared with all other users.
     * Get dashboard
     */
    async getDashboardRaw(requestParameters: GetDashboardRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Dashboard>> {
        const requestOptions = await this.getDashboardRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response);
    }

    /**
     * Returns a dashboard.  This operation can be accessed anonymously.  **[Permissions](#permissions) required:** None.  However, to get a dashboard, the dashboard must be shared with the user or the user must own it. Note, users with the *Administer Jira* [global permission](https://confluence.atlassian.com/x/x4dKLg) are considered owners of the System dashboard. The System dashboard is considered to be shared with all other users.
     * Get dashboard
     */
    async getDashboard(requestParameters: GetDashboardRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Dashboard> {
        const response = await this.getDashboardRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getDashboardItemProperty without sending the request
     */
    async getDashboardItemPropertyRequestOpts(requestParameters: GetDashboardItemPropertyRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['dashboardId'] == null) {
            throw new runtime.RequiredError(
                'dashboardId',
                'Required parameter "dashboardId" was null or undefined when calling getDashboardItemProperty().'
            );
        }

        if (requestParameters['itemId'] == null) {
            throw new runtime.RequiredError(
                'itemId',
                'Required parameter "itemId" was null or undefined when calling getDashboardItemProperty().'
            );
        }

        if (requestParameters['propertyKey'] == null) {
            throw new runtime.RequiredError(
                'propertyKey',
                'Required parameter "propertyKey" was null or undefined when calling getDashboardItemProperty().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("OAuth2", ["read:jira-work"]);
        }

        if (this.configuration && (this.configuration.username !== undefined || this.configuration.password !== undefined)) {
            headerParameters["Authorization"] = "Basic " + btoa(this.configuration.username + ":" + this.configuration.password);
        }

        let urlPath = `/rest/api/3/dashboard/{dashboardId}/items/{itemId}/properties/{propertyKey}`;
        urlPath = urlPath.replace(`{${"dashboardId"}}`, encodeURIComponent(String(requestParameters['dashboardId'])));
        urlPath = urlPath.replace(`{${"itemId"}}`, encodeURIComponent(String(requestParameters['itemId'])));
        urlPath = urlPath.replace(`{${"propertyKey"}}`, encodeURIComponent(String(requestParameters['propertyKey'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Returns the key and value of a dashboard item property.  A dashboard item enables an app to add user-specific information to a user dashboard. Dashboard items are exposed to users as gadgets that users can add to their dashboards. For more information on how users do this, see [Adding and customizing gadgets](https://confluence.atlassian.com/x/7AeiLQ).  When an app creates a dashboard item it registers a callback to receive the dashboard item ID. The callback fires whenever the item is rendered or, where the item is configurable, the user edits the item. The app then uses this resource to store the item\'s content or configuration details. For more information on working with dashboard items, see [ Building a dashboard item for a JIRA Connect add-on](https://developer.atlassian.com/server/jira/platform/guide-building-a-dashboard-item-for-a-jira-connect-add-on-33746254/) and the [Dashboard Item](https://developer.atlassian.com/cloud/jira/platform/modules/dashboard-item/) documentation.  There is no resource to set or get dashboard items.  This operation can be accessed anonymously.  **[Permissions](#permissions) required:** The user must have read permission of the dashboard or have the dashboard shared with them.
     * Get dashboard item property
     */
    async getDashboardItemPropertyRaw(requestParameters: GetDashboardItemPropertyRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<EntityProperty>> {
        const requestOptions = await this.getDashboardItemPropertyRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response);
    }

    /**
     * Returns the key and value of a dashboard item property.  A dashboard item enables an app to add user-specific information to a user dashboard. Dashboard items are exposed to users as gadgets that users can add to their dashboards. For more information on how users do this, see [Adding and customizing gadgets](https://confluence.atlassian.com/x/7AeiLQ).  When an app creates a dashboard item it registers a callback to receive the dashboard item ID. The callback fires whenever the item is rendered or, where the item is configurable, the user edits the item. The app then uses this resource to store the item\'s content or configuration details. For more information on working with dashboard items, see [ Building a dashboard item for a JIRA Connect add-on](https://developer.atlassian.com/server/jira/platform/guide-building-a-dashboard-item-for-a-jira-connect-add-on-33746254/) and the [Dashboard Item](https://developer.atlassian.com/cloud/jira/platform/modules/dashboard-item/) documentation.  There is no resource to set or get dashboard items.  This operation can be accessed anonymously.  **[Permissions](#permissions) required:** The user must have read permission of the dashboard or have the dashboard shared with them.
     * Get dashboard item property
     */
    async getDashboardItemProperty(requestParameters: GetDashboardItemPropertyRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<EntityProperty> {
        const response = await this.getDashboardItemPropertyRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getDashboardItemPropertyKeys without sending the request
     */
    async getDashboardItemPropertyKeysRequestOpts(requestParameters: GetDashboardItemPropertyKeysRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['dashboardId'] == null) {
            throw new runtime.RequiredError(
                'dashboardId',
                'Required parameter "dashboardId" was null or undefined when calling getDashboardItemPropertyKeys().'
            );
        }

        if (requestParameters['itemId'] == null) {
            throw new runtime.RequiredError(
                'itemId',
                'Required parameter "itemId" was null or undefined when calling getDashboardItemPropertyKeys().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("OAuth2", ["read:jira-work"]);
        }

        if (this.configuration && (this.configuration.username !== undefined || this.configuration.password !== undefined)) {
            headerParameters["Authorization"] = "Basic " + btoa(this.configuration.username + ":" + this.configuration.password);
        }

        let urlPath = `/rest/api/3/dashboard/{dashboardId}/items/{itemId}/properties`;
        urlPath = urlPath.replace(`{${"dashboardId"}}`, encodeURIComponent(String(requestParameters['dashboardId'])));
        urlPath = urlPath.replace(`{${"itemId"}}`, encodeURIComponent(String(requestParameters['itemId'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Returns the keys of all properties for a dashboard item.  This operation can be accessed anonymously.  **[Permissions](#permissions) required:** The user must have read permission of the dashboard or have the dashboard shared with them.
     * Get dashboard item property keys
     */
    async getDashboardItemPropertyKeysRaw(requestParameters: GetDashboardItemPropertyKeysRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PropertyKeys>> {
        const requestOptions = await this.getDashboardItemPropertyKeysRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response);
    }

    /**
     * Returns the keys of all properties for a dashboard item.  This operation can be accessed anonymously.  **[Permissions](#permissions) required:** The user must have read permission of the dashboard or have the dashboard shared with them.
     * Get dashboard item property keys
     */
    async getDashboardItemPropertyKeys(requestParameters: GetDashboardItemPropertyKeysRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PropertyKeys> {
        const response = await this.getDashboardItemPropertyKeysRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getDashboardsPaginated without sending the request
     */
    async getDashboardsPaginatedRequestOpts(requestParameters: GetDashboardsPaginatedRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        if (requestParameters['dashboardName'] != null) {
            queryParameters['dashboardName'] = requestParameters['dashboardName'];
        }

        if (requestParameters['accountId'] != null) {
            queryParameters['accountId'] = requestParameters['accountId'];
        }

        if (requestParameters['owner'] != null) {
            queryParameters['owner'] = requestParameters['owner'];
        }

        if (requestParameters['groupname'] != null) {
            queryParameters['groupname'] = requestParameters['groupname'];
        }

        if (requestParameters['groupId'] != null) {
            queryParameters['groupId'] = requestParameters['groupId'];
        }

        if (requestParameters['projectId'] != null) {
            queryParameters['projectId'] = requestParameters['projectId'];
        }

        if (requestParameters['orderBy'] != null) {
            queryParameters['orderBy'] = requestParameters['orderBy'];
        }

        if (requestParameters['startAt'] != null) {
            queryParameters['startAt'] = requestParameters['startAt'];
        }

        if (requestParameters['maxResults'] != null) {
            queryParameters['maxResults'] = requestParameters['maxResults'];
        }

        if (requestParameters['status'] != null) {
            queryParameters['status'] = requestParameters['status'];
        }

        if (requestParameters['expand'] != null) {
            queryParameters['expand'] = requestParameters['expand'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("OAuth2", ["read:jira-work"]);
        }

        if (this.configuration && (this.configuration.username !== undefined || this.configuration.password !== undefined)) {
            headerParameters["Authorization"] = "Basic " + btoa(this.configuration.username + ":" + this.configuration.password);
        }

        let urlPath = `/rest/api/3/dashboard/search`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Returns a [paginated](#pagination) list of dashboards. This operation is similar to [Get dashboards](#api-rest-api-3-dashboard-get) except that the results can be refined to include dashboards that have specific attributes. For example, dashboards with a particular name. When multiple attributes are specified only filters matching all attributes are returned.  This operation can be accessed anonymously.  **[Permissions](#permissions) required:** The following dashboards that match the query parameters are returned:   *  Dashboards owned by the user. Not returned for anonymous users.  *  Dashboards shared with a group that the user is a member of. Not returned for anonymous users.  *  Dashboards shared with a private project that the user can browse. Not returned for anonymous users.  *  Dashboards shared with a public project.  *  Dashboards shared with the public.
     * Search for dashboards
     */
    async getDashboardsPaginatedRaw(requestParameters: GetDashboardsPaginatedRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PageBeanDashboard>> {
        const requestOptions = await this.getDashboardsPaginatedRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response);
    }

    /**
     * Returns a [paginated](#pagination) list of dashboards. This operation is similar to [Get dashboards](#api-rest-api-3-dashboard-get) except that the results can be refined to include dashboards that have specific attributes. For example, dashboards with a particular name. When multiple attributes are specified only filters matching all attributes are returned.  This operation can be accessed anonymously.  **[Permissions](#permissions) required:** The following dashboards that match the query parameters are returned:   *  Dashboards owned by the user. Not returned for anonymous users.  *  Dashboards shared with a group that the user is a member of. Not returned for anonymous users.  *  Dashboards shared with a private project that the user can browse. Not returned for anonymous users.  *  Dashboards shared with a public project.  *  Dashboards shared with the public.
     * Search for dashboards
     */
    async getDashboardsPaginated(requestParameters: GetDashboardsPaginatedRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PageBeanDashboard> {
        const response = await this.getDashboardsPaginatedRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for removeGadget without sending the request
     */
    async removeGadgetRequestOpts(requestParameters: RemoveGadgetRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['dashboardId'] == null) {
            throw new runtime.RequiredError(
                'dashboardId',
                'Required parameter "dashboardId" was null or undefined when calling removeGadget().'
            );
        }

        if (requestParameters['gadgetId'] == null) {
            throw new runtime.RequiredError(
                'gadgetId',
                'Required parameter "gadgetId" was null or undefined when calling removeGadget().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("OAuth2", ["write:jira-work"]);
        }

        if (this.configuration && (this.configuration.username !== undefined || this.configuration.password !== undefined)) {
            headerParameters["Authorization"] = "Basic " + btoa(this.configuration.username + ":" + this.configuration.password);
        }

        let urlPath = `/rest/api/3/dashboard/{dashboardId}/gadget/{gadgetId}`;
        urlPath = urlPath.replace(`{${"dashboardId"}}`, encodeURIComponent(String(requestParameters['dashboardId'])));
        urlPath = urlPath.replace(`{${"gadgetId"}}`, encodeURIComponent(String(requestParameters['gadgetId'])));

        return {
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Removes a dashboard gadget from a dashboard.  When a gadget is removed from a dashboard, other gadgets in the same column are moved up to fill the emptied position.  **[Permissions](#permissions) required:** None.
     * Remove gadget from dashboard
     */
    async removeGadgetRaw(requestParameters: RemoveGadgetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>> {
        const requestOptions = await this.removeGadgetRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<any>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Removes a dashboard gadget from a dashboard.  When a gadget is removed from a dashboard, other gadgets in the same column are moved up to fill the emptied position.  **[Permissions](#permissions) required:** None.
     * Remove gadget from dashboard
     */
    async removeGadget(requestParameters: RemoveGadgetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any> {
        const response = await this.removeGadgetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for setDashboardItemProperty without sending the request
     */
    async setDashboardItemPropertyRequestOpts(requestParameters: SetDashboardItemPropertyRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['dashboardId'] == null) {
            throw new runtime.RequiredError(
                'dashboardId',
                'Required parameter "dashboardId" was null or undefined when calling setDashboardItemProperty().'
            );
        }

        if (requestParameters['itemId'] == null) {
            throw new runtime.RequiredError(
                'itemId',
                'Required parameter "itemId" was null or undefined when calling setDashboardItemProperty().'
            );
        }

        if (requestParameters['propertyKey'] == null) {
            throw new runtime.RequiredError(
                'propertyKey',
                'Required parameter "propertyKey" was null or undefined when calling setDashboardItemProperty().'
            );
        }

        if (requestParameters['body'] == null) {
            throw new runtime.RequiredError(
                'body',
                'Required parameter "body" was null or undefined when calling setDashboardItemProperty().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("OAuth2", ["write:jira-work"]);
        }

        if (this.configuration && (this.configuration.username !== undefined || this.configuration.password !== undefined)) {
            headerParameters["Authorization"] = "Basic " + btoa(this.configuration.username + ":" + this.configuration.password);
        }

        let urlPath = `/rest/api/3/dashboard/{dashboardId}/items/{itemId}/properties/{propertyKey}`;
        urlPath = urlPath.replace(`{${"dashboardId"}}`, encodeURIComponent(String(requestParameters['dashboardId'])));
        urlPath = urlPath.replace(`{${"itemId"}}`, encodeURIComponent(String(requestParameters['itemId'])));
        urlPath = urlPath.replace(`{${"propertyKey"}}`, encodeURIComponent(String(requestParameters['propertyKey'])));

        return {
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters['body'] as any,
        };
    }

    /**
     * Sets the value of a dashboard item property. Use this resource in apps to store custom data against a dashboard item.  A dashboard item enables an app to add user-specific information to a user dashboard. Dashboard items are exposed to users as gadgets that users can add to their dashboards. For more information on how users do this, see [Adding and customizing gadgets](https://confluence.atlassian.com/x/7AeiLQ).  When an app creates a dashboard item it registers a callback to receive the dashboard item ID. The callback fires whenever the item is rendered or, where the item is configurable, the user edits the item. The app then uses this resource to store the item\'s content or configuration details. For more information on working with dashboard items, see [ Building a dashboard item for a JIRA Connect add-on](https://developer.atlassian.com/server/jira/platform/guide-building-a-dashboard-item-for-a-jira-connect-add-on-33746254/) and the [Dashboard Item](https://developer.atlassian.com/cloud/jira/platform/modules/dashboard-item/) documentation.  There is no resource to set or get dashboard items.  The value of the request body must be a [valid](http://tools.ietf.org/html/rfc4627), non-empty JSON blob. The maximum length is 32768 characters.  This operation can be accessed anonymously.  **[Permissions](#permissions) required:** The user must have edit permisson of the dashboard.
     * Set dashboard item property
     */
    async setDashboardItemPropertyRaw(requestParameters: SetDashboardItemPropertyRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>> {
        const requestOptions = await this.setDashboardItemPropertyRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<any>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Sets the value of a dashboard item property. Use this resource in apps to store custom data against a dashboard item.  A dashboard item enables an app to add user-specific information to a user dashboard. Dashboard items are exposed to users as gadgets that users can add to their dashboards. For more information on how users do this, see [Adding and customizing gadgets](https://confluence.atlassian.com/x/7AeiLQ).  When an app creates a dashboard item it registers a callback to receive the dashboard item ID. The callback fires whenever the item is rendered or, where the item is configurable, the user edits the item. The app then uses this resource to store the item\'s content or configuration details. For more information on working with dashboard items, see [ Building a dashboard item for a JIRA Connect add-on](https://developer.atlassian.com/server/jira/platform/guide-building-a-dashboard-item-for-a-jira-connect-add-on-33746254/) and the [Dashboard Item](https://developer.atlassian.com/cloud/jira/platform/modules/dashboard-item/) documentation.  There is no resource to set or get dashboard items.  The value of the request body must be a [valid](http://tools.ietf.org/html/rfc4627), non-empty JSON blob. The maximum length is 32768 characters.  This operation can be accessed anonymously.  **[Permissions](#permissions) required:** The user must have edit permisson of the dashboard.
     * Set dashboard item property
     */
    async setDashboardItemProperty(requestParameters: SetDashboardItemPropertyRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any> {
        const response = await this.setDashboardItemPropertyRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for updateDashboard without sending the request
     */
    async updateDashboardRequestOpts(requestParameters: UpdateDashboardRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling updateDashboard().'
            );
        }

        if (requestParameters['dashboardDetails'] == null) {
            throw new runtime.RequiredError(
                'dashboardDetails',
                'Required parameter "dashboardDetails" was null or undefined when calling updateDashboard().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['extendAdminPermissions'] != null) {
            queryParameters['extendAdminPermissions'] = requestParameters['extendAdminPermissions'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("OAuth2", ["write:jira-work"]);
        }

        if (this.configuration && (this.configuration.username !== undefined || this.configuration.password !== undefined)) {
            headerParameters["Authorization"] = "Basic " + btoa(this.configuration.username + ":" + this.configuration.password);
        }

        let urlPath = `/rest/api/3/dashboard/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters['dashboardDetails'],
        };
    }

    /**
     * Updates a dashboard, replacing all the dashboard details with those provided.  **[Permissions](#permissions) required:** None  The dashboard to be updated must be owned by the user.
     * Update dashboard
     */
    async updateDashboardRaw(requestParameters: UpdateDashboardRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Dashboard>> {
        const requestOptions = await this.updateDashboardRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response);
    }

    /**
     * Updates a dashboard, replacing all the dashboard details with those provided.  **[Permissions](#permissions) required:** None  The dashboard to be updated must be owned by the user.
     * Update dashboard
     */
    async updateDashboard(requestParameters: UpdateDashboardRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Dashboard> {
        const response = await this.updateDashboardRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for updateGadget without sending the request
     */
    async updateGadgetRequestOpts(requestParameters: UpdateGadgetRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['dashboardId'] == null) {
            throw new runtime.RequiredError(
                'dashboardId',
                'Required parameter "dashboardId" was null or undefined when calling updateGadget().'
            );
        }

        if (requestParameters['gadgetId'] == null) {
            throw new runtime.RequiredError(
                'gadgetId',
                'Required parameter "gadgetId" was null or undefined when calling updateGadget().'
            );
        }

        if (requestParameters['dashboardGadgetUpdateRequest'] == null) {
            throw new runtime.RequiredError(
                'dashboardGadgetUpdateRequest',
                'Required parameter "dashboardGadgetUpdateRequest" was null or undefined when calling updateGadget().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("OAuth2", ["write:jira-work"]);
        }

        if (this.configuration && (this.configuration.username !== undefined || this.configuration.password !== undefined)) {
            headerParameters["Authorization"] = "Basic " + btoa(this.configuration.username + ":" + this.configuration.password);
        }

        let urlPath = `/rest/api/3/dashboard/{dashboardId}/gadget/{gadgetId}`;
        urlPath = urlPath.replace(`{${"dashboardId"}}`, encodeURIComponent(String(requestParameters['dashboardId'])));
        urlPath = urlPath.replace(`{${"gadgetId"}}`, encodeURIComponent(String(requestParameters['gadgetId'])));

        return {
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters['dashboardGadgetUpdateRequest'],
        };
    }

    /**
     * Changes the title, position, and color of the gadget on a dashboard.  **[Permissions](#permissions) required:** None.
     * Update gadget on dashboard
     */
    async updateGadgetRaw(requestParameters: UpdateGadgetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>> {
        const requestOptions = await this.updateGadgetRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<any>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Changes the title, position, and color of the gadget on a dashboard.  **[Permissions](#permissions) required:** None.
     * Update gadget on dashboard
     */
    async updateGadget(requestParameters: UpdateGadgetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any> {
        const response = await this.updateGadgetRaw(requestParameters, initOverrides);
        return await response.value();
    }

}

/**
 * @export
 */
export const GetAllDashboardsFilterEnum = {
    My: 'my',
    Favourite: 'favourite'
} as const;
export type GetAllDashboardsFilterEnum = typeof GetAllDashboardsFilterEnum[keyof typeof GetAllDashboardsFilterEnum];
/**
 * @export
 */
export const GetDashboardsPaginatedOrderByEnum = {
    Description: 'description',
    Description2Desc: '-description',
    Description3Asc: '+description',
    FavoriteCount: 'favorite_count',
    FavoriteCount2Desc: '-favorite_count',
    FavoriteCount3Asc: '+favorite_count',
    Id: 'id',
    Id2Desc: '-id',
    Id3Asc: '+id',
    IsFavorite: 'is_favorite',
    IsFavorite2Desc: '-is_favorite',
    IsFavorite3Asc: '+is_favorite',
    Name: 'name',
    Name2Desc: '-name',
    Name3Asc: '+name',
    Owner: 'owner',
    Owner2Desc: '-owner',
    Owner3Asc: '+owner'
} as const;
export type GetDashboardsPaginatedOrderByEnum = typeof GetDashboardsPaginatedOrderByEnum[keyof typeof GetDashboardsPaginatedOrderByEnum];
/**
 * @export
 */
export const GetDashboardsPaginatedStatusEnum = {
    Active: 'active',
    Archived: 'archived',
    Deleted: 'deleted'
} as const;
export type GetDashboardsPaginatedStatusEnum = typeof GetDashboardsPaginatedStatusEnum[keyof typeof GetDashboardsPaginatedStatusEnum];
