/* tslint:disable */
/* eslint-disable */
/**
 * The Jira Cloud platform REST API
 * Jira Cloud platform REST API documentation
 *
 * The version of the OpenAPI document: 1001.0.0-SNAPSHOT-21695d0ffb3094632d6272be3e6600848f05a23b
 * Contact: ecosystem@atlassian.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  ConnectModules,
  ErrorMessage,
} from '../models/index';

export interface DynamicModulesResourceRegisterModulesPostRequest {
    connectModules: ConnectModules;
}

export interface DynamicModulesResourceRemoveModulesDeleteRequest {
    moduleKey?: Array<string>;
}

/**
 * 
 */
export class DynamicModulesApi extends runtime.BaseAPI {

    /**
     * Creates request options for dynamicModulesResourceGetModulesGet without sending the request
     */
    async dynamicModulesResourceGetModulesGetRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/rest/atlassian-connect/1/app/module/dynamic`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Returns all modules registered dynamically by the calling app.  **[Permissions](#permissions) required:** Only Connect apps can make this request.
     * Get modules
     */
    async dynamicModulesResourceGetModulesGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ConnectModules>> {
        const requestOptions = await this.dynamicModulesResourceGetModulesGetRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response);
    }

    /**
     * Returns all modules registered dynamically by the calling app.  **[Permissions](#permissions) required:** Only Connect apps can make this request.
     * Get modules
     */
    async dynamicModulesResourceGetModulesGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ConnectModules> {
        const response = await this.dynamicModulesResourceGetModulesGetRaw(initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for dynamicModulesResourceRegisterModulesPost without sending the request
     */
    async dynamicModulesResourceRegisterModulesPostRequestOpts(requestParameters: DynamicModulesResourceRegisterModulesPostRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['connectModules'] == null) {
            throw new runtime.RequiredError(
                'connectModules',
                'Required parameter "connectModules" was null or undefined when calling dynamicModulesResourceRegisterModulesPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/rest/atlassian-connect/1/app/module/dynamic`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters['connectModules'],
        };
    }

    /**
     * Registers a list of modules.  **[Permissions](#permissions) required:** Only Connect apps can make this request.
     * Register modules
     */
    async dynamicModulesResourceRegisterModulesPostRaw(requestParameters: DynamicModulesResourceRegisterModulesPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.dynamicModulesResourceRegisterModulesPostRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Registers a list of modules.  **[Permissions](#permissions) required:** Only Connect apps can make this request.
     * Register modules
     */
    async dynamicModulesResourceRegisterModulesPost(requestParameters: DynamicModulesResourceRegisterModulesPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.dynamicModulesResourceRegisterModulesPostRaw(requestParameters, initOverrides);
    }

    /**
     * Creates request options for dynamicModulesResourceRemoveModulesDelete without sending the request
     */
    async dynamicModulesResourceRemoveModulesDeleteRequestOpts(requestParameters: DynamicModulesResourceRemoveModulesDeleteRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        if (requestParameters['moduleKey'] != null) {
            queryParameters['moduleKey'] = requestParameters['moduleKey'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/rest/atlassian-connect/1/app/module/dynamic`;

        return {
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Remove all or a list of modules registered by the calling app.  **[Permissions](#permissions) required:** Only Connect apps can make this request.
     * Remove modules
     */
    async dynamicModulesResourceRemoveModulesDeleteRaw(requestParameters: DynamicModulesResourceRemoveModulesDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.dynamicModulesResourceRemoveModulesDeleteRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Remove all or a list of modules registered by the calling app.  **[Permissions](#permissions) required:** Only Connect apps can make this request.
     * Remove modules
     */
    async dynamicModulesResourceRemoveModulesDelete(requestParameters: DynamicModulesResourceRemoveModulesDeleteRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.dynamicModulesResourceRemoveModulesDeleteRaw(requestParameters, initOverrides);
    }

}
