/* tslint:disable */
/* eslint-disable */
/**
 * The Jira Cloud platform REST API
 * Jira Cloud platform REST API documentation
 *
 * The version of the OpenAPI document: 1001.0.0-SNAPSHOT-21695d0ffb3094632d6272be3e6600848f05a23b
 * Contact: ecosystem@atlassian.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  ErrorCollection,
  License,
  LicenseMetric,
} from '../models/index';

export interface GetApproximateApplicationLicenseCountRequest {
    applicationKey: GetApproximateApplicationLicenseCountApplicationKeyEnum;
}

/**
 * 
 */
export class LicenseMetricsApi extends runtime.BaseAPI {

    /**
     * Creates request options for getApproximateApplicationLicenseCount without sending the request
     */
    async getApproximateApplicationLicenseCountRequestOpts(requestParameters: GetApproximateApplicationLicenseCountRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['applicationKey'] == null) {
            throw new runtime.RequiredError(
                'applicationKey',
                'Required parameter "applicationKey" was null or undefined when calling getApproximateApplicationLicenseCount().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("OAuth2", ["manage:jira-configuration"]);
        }

        if (this.configuration && (this.configuration.username !== undefined || this.configuration.password !== undefined)) {
            headerParameters["Authorization"] = "Basic " + btoa(this.configuration.username + ":" + this.configuration.password);
        }

        let urlPath = `/rest/api/3/license/approximateLicenseCount/product/{applicationKey}`;
        urlPath = urlPath.replace(`{${"applicationKey"}}`, encodeURIComponent(String(requestParameters['applicationKey'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Returns the total approximate number of user accounts for a single Jira license. Note that this information is cached with a 7-day lifecycle and could be stale at the time of call.  **[Permissions](#permissions) required:** *Administer Jira* [global permission](https://confluence.atlassian.com/x/x4dKLg).
     * Get approximate application license count
     */
    async getApproximateApplicationLicenseCountRaw(requestParameters: GetApproximateApplicationLicenseCountRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<LicenseMetric>> {
        const requestOptions = await this.getApproximateApplicationLicenseCountRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response);
    }

    /**
     * Returns the total approximate number of user accounts for a single Jira license. Note that this information is cached with a 7-day lifecycle and could be stale at the time of call.  **[Permissions](#permissions) required:** *Administer Jira* [global permission](https://confluence.atlassian.com/x/x4dKLg).
     * Get approximate application license count
     */
    async getApproximateApplicationLicenseCount(requestParameters: GetApproximateApplicationLicenseCountRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<LicenseMetric> {
        const response = await this.getApproximateApplicationLicenseCountRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getApproximateLicenseCount without sending the request
     */
    async getApproximateLicenseCountRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("OAuth2", ["manage:jira-configuration"]);
        }

        if (this.configuration && (this.configuration.username !== undefined || this.configuration.password !== undefined)) {
            headerParameters["Authorization"] = "Basic " + btoa(this.configuration.username + ":" + this.configuration.password);
        }

        let urlPath = `/rest/api/3/license/approximateLicenseCount`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Returns the approximate number of user accounts across all Jira licenses. Note that this information is cached with a 7-day lifecycle and could be stale at the time of call.  **[Permissions](#permissions) required:** *Administer Jira* [global permission](https://confluence.atlassian.com/x/x4dKLg).
     * Get approximate license count
     */
    async getApproximateLicenseCountRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<LicenseMetric>> {
        const requestOptions = await this.getApproximateLicenseCountRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response);
    }

    /**
     * Returns the approximate number of user accounts across all Jira licenses. Note that this information is cached with a 7-day lifecycle and could be stale at the time of call.  **[Permissions](#permissions) required:** *Administer Jira* [global permission](https://confluence.atlassian.com/x/x4dKLg).
     * Get approximate license count
     */
    async getApproximateLicenseCount(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<LicenseMetric> {
        const response = await this.getApproximateLicenseCountRaw(initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getLicense without sending the request
     */
    async getLicenseRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("OAuth2", ["manage:jira-configuration"]);
        }

        if (this.configuration && (this.configuration.username !== undefined || this.configuration.password !== undefined)) {
            headerParameters["Authorization"] = "Basic " + btoa(this.configuration.username + ":" + this.configuration.password);
        }

        let urlPath = `/rest/api/3/instance/license`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Returns licensing information about the Jira instance.  **[Permissions](#permissions) required:** None.
     * Get license
     */
    async getLicenseRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<License>> {
        const requestOptions = await this.getLicenseRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response);
    }

    /**
     * Returns licensing information about the Jira instance.  **[Permissions](#permissions) required:** None.
     * Get license
     */
    async getLicense(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<License> {
        const response = await this.getLicenseRaw(initOverrides);
        return await response.value();
    }

}

/**
 * @export
 */
export const GetApproximateApplicationLicenseCountApplicationKeyEnum = {
    JiraCore: 'jira-core',
    JiraProductDiscovery: 'jira-product-discovery',
    JiraSoftware: 'jira-software',
    JiraServicedesk: 'jira-servicedesk'
} as const;
export type GetApproximateApplicationLicenseCountApplicationKeyEnum = typeof GetApproximateApplicationLicenseCountApplicationKeyEnum[keyof typeof GetApproximateApplicationLicenseCountApplicationKeyEnum];
