/* tslint:disable */
/* eslint-disable */
/**
 * The Jira Cloud platform REST API
 * Jira Cloud platform REST API documentation
 *
 * The version of the OpenAPI document: 1001.0.0-SNAPSHOT-e54f3aeddae545dd970b98a1ac06d32cf9f54b1a
 * Contact: ecosystem@atlassian.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import type {
    UpdateDefaultProjectClassificationBean,
} from '../models/index';

export interface GetDefaultProjectClassificationRequest {
    projectIdOrKey: string;
}

export interface GetProjectClassificationConfigRequest {
    projectIdOrKey: string;
}

export interface RemoveDefaultProjectClassificationRequest {
    projectIdOrKey: string;
}

export interface UpdateDefaultProjectClassificationRequest {
    projectIdOrKey: string;
    updateDefaultProjectClassificationBean: UpdateDefaultProjectClassificationBean;
}

/**
 * 
 */
export class ProjectClassificationLevelsApi extends runtime.BaseAPI {

    /**
     * Creates request options for getDefaultProjectClassification without sending the request
     */
    async getDefaultProjectClassificationRequestOpts(requestParameters: GetDefaultProjectClassificationRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['projectIdOrKey'] == null) {
            throw new runtime.RequiredError(
                'projectIdOrKey',
                'Required parameter "projectIdOrKey" was null or undefined when calling getDefaultProjectClassification().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("OAuth2", ["read:jira-work"]);
        }

        if (this.configuration && (this.configuration.username !== undefined || this.configuration.password !== undefined)) {
            headerParameters["Authorization"] = "Basic " + btoa(this.configuration.username + ":" + this.configuration.password);
        }

        let urlPath = `/rest/api/3/project/{projectIdOrKey}/classification-level/default`;
        urlPath = urlPath.replace('{projectIdOrKey}', encodeURIComponent(String(requestParameters['projectIdOrKey'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Returns the default data classification for a project.  **[Permissions](#permissions) required:**   *  *Browse Projects* [project permission](https://confluence.atlassian.com/x/yodKLg) for the project.  *  *Administer projects* [project permission](https://confluence.atlassian.com/x/yodKLg) for the project.  *  *Administer jira* [global permission](https://confluence.atlassian.com/x/x4dKLg).
     * Get the default data classification level of a project
     */
    async getDefaultProjectClassificationRaw(requestParameters: GetDefaultProjectClassificationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>> {
        const requestOptions = await this.getDefaultProjectClassificationRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<any>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Returns the default data classification for a project.  **[Permissions](#permissions) required:**   *  *Browse Projects* [project permission](https://confluence.atlassian.com/x/yodKLg) for the project.  *  *Administer projects* [project permission](https://confluence.atlassian.com/x/yodKLg) for the project.  *  *Administer jira* [global permission](https://confluence.atlassian.com/x/x4dKLg).
     * Get the default data classification level of a project
     */
    async getDefaultProjectClassification(requestParameters: GetDefaultProjectClassificationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any> {
        const response = await this.getDefaultProjectClassificationRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getProjectClassificationConfig without sending the request
     */
    async getProjectClassificationConfigRequestOpts(requestParameters: GetProjectClassificationConfigRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['projectIdOrKey'] == null) {
            throw new runtime.RequiredError(
                'projectIdOrKey',
                'Required parameter "projectIdOrKey" was null or undefined when calling getProjectClassificationConfig().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("OAuth2", ["read:jira-work"]);
        }

        if (this.configuration && (this.configuration.username !== undefined || this.configuration.password !== undefined)) {
            headerParameters["Authorization"] = "Basic " + btoa(this.configuration.username + ":" + this.configuration.password);
        }

        let urlPath = `/rest/api/3/project/{projectIdOrKey}/classification-config`;
        urlPath = urlPath.replace('{projectIdOrKey}', encodeURIComponent(String(requestParameters['projectIdOrKey'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Returns the consolidated classification configuration for a project\'s admin settings page.  This includes permitted classification levels (with status), the project\'s default classification level, the organization\'s default classification level, and the container override setting.  **[Permissions](#permissions) required:**   *  *Browse Projects* [project permission](https://confluence.atlassian.com/x/yodKLg) for the project.  *  *Administer projects* [project permission](https://confluence.atlassian.com/x/yodKLg) for the project.  *  *Administer jira* [global permission](https://confluence.atlassian.com/x/x4dKLg).
     * Get the classification configuration for a project
     */
    async getProjectClassificationConfigRaw(requestParameters: GetProjectClassificationConfigRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>> {
        const requestOptions = await this.getProjectClassificationConfigRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<any>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Returns the consolidated classification configuration for a project\'s admin settings page.  This includes permitted classification levels (with status), the project\'s default classification level, the organization\'s default classification level, and the container override setting.  **[Permissions](#permissions) required:**   *  *Browse Projects* [project permission](https://confluence.atlassian.com/x/yodKLg) for the project.  *  *Administer projects* [project permission](https://confluence.atlassian.com/x/yodKLg) for the project.  *  *Administer jira* [global permission](https://confluence.atlassian.com/x/x4dKLg).
     * Get the classification configuration for a project
     */
    async getProjectClassificationConfig(requestParameters: GetProjectClassificationConfigRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any> {
        const response = await this.getProjectClassificationConfigRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for removeDefaultProjectClassification without sending the request
     */
    async removeDefaultProjectClassificationRequestOpts(requestParameters: RemoveDefaultProjectClassificationRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['projectIdOrKey'] == null) {
            throw new runtime.RequiredError(
                'projectIdOrKey',
                'Required parameter "projectIdOrKey" was null or undefined when calling removeDefaultProjectClassification().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("OAuth2", ["manage:jira-project"]);
        }

        if (this.configuration && (this.configuration.username !== undefined || this.configuration.password !== undefined)) {
            headerParameters["Authorization"] = "Basic " + btoa(this.configuration.username + ":" + this.configuration.password);
        }

        let urlPath = `/rest/api/3/project/{projectIdOrKey}/classification-level/default`;
        urlPath = urlPath.replace('{projectIdOrKey}', encodeURIComponent(String(requestParameters['projectIdOrKey'])));

        return {
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Remove the default data classification level for a project.  **[Permissions](#permissions) required:**   *  *Administer projects* [project permission](https://confluence.atlassian.com/x/yodKLg) for the project.  *  *Administer jira* [global permission](https://confluence.atlassian.com/x/x4dKLg).
     * Remove the default data classification level from a project
     */
    async removeDefaultProjectClassificationRaw(requestParameters: RemoveDefaultProjectClassificationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>> {
        const requestOptions = await this.removeDefaultProjectClassificationRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<any>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Remove the default data classification level for a project.  **[Permissions](#permissions) required:**   *  *Administer projects* [project permission](https://confluence.atlassian.com/x/yodKLg) for the project.  *  *Administer jira* [global permission](https://confluence.atlassian.com/x/x4dKLg).
     * Remove the default data classification level from a project
     */
    async removeDefaultProjectClassification(requestParameters: RemoveDefaultProjectClassificationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any> {
        const response = await this.removeDefaultProjectClassificationRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for updateDefaultProjectClassification without sending the request
     */
    async updateDefaultProjectClassificationRequestOpts(requestParameters: UpdateDefaultProjectClassificationRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['projectIdOrKey'] == null) {
            throw new runtime.RequiredError(
                'projectIdOrKey',
                'Required parameter "projectIdOrKey" was null or undefined when calling updateDefaultProjectClassification().'
            );
        }

        if (requestParameters['updateDefaultProjectClassificationBean'] == null) {
            throw new runtime.RequiredError(
                'updateDefaultProjectClassificationBean',
                'Required parameter "updateDefaultProjectClassificationBean" was null or undefined when calling updateDefaultProjectClassification().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("OAuth2", ["manage:jira-project"]);
        }

        if (this.configuration && (this.configuration.username !== undefined || this.configuration.password !== undefined)) {
            headerParameters["Authorization"] = "Basic " + btoa(this.configuration.username + ":" + this.configuration.password);
        }

        let urlPath = `/rest/api/3/project/{projectIdOrKey}/classification-level/default`;
        urlPath = urlPath.replace('{projectIdOrKey}', encodeURIComponent(String(requestParameters['projectIdOrKey'])));

        return {
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters['updateDefaultProjectClassificationBean'],
        };
    }

    /**
     * Updates the default data classification level for a project.  **[Permissions](#permissions) required:**   *  *Administer projects* [project permission](https://confluence.atlassian.com/x/yodKLg) for the project.  *  *Administer jira* [global permission](https://confluence.atlassian.com/x/x4dKLg).
     * Update the default data classification level of a project
     */
    async updateDefaultProjectClassificationRaw(requestParameters: UpdateDefaultProjectClassificationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>> {
        const requestOptions = await this.updateDefaultProjectClassificationRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<any>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Updates the default data classification level for a project.  **[Permissions](#permissions) required:**   *  *Administer projects* [project permission](https://confluence.atlassian.com/x/yodKLg) for the project.  *  *Administer jira* [global permission](https://confluence.atlassian.com/x/x4dKLg).
     * Update the default data classification level of a project
     */
    async updateDefaultProjectClassification(requestParameters: UpdateDefaultProjectClassificationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any> {
        const response = await this.updateDefaultProjectClassificationRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
