enableGlobalCache: false

nodeLinker: node-modules

yarnPath: .yarn/releases/yarn-4.18.0.cjs

npmAuditExcludePackages:
  - browserslist # is not relevant for plain js code (https://github.com/advisories/GHSA-73wf-gq98-2v4g)

npmAuditIgnoreAdvisories:
