/* tslint:disable */
/* eslint-disable */
/**
 * The Confluence Cloud REST API v2
 * This document describes Confluence\'s v2 APIs. This is intended to be an iteration on the existing Confluence Cloud REST API with improvements in both endpoint definitions and performance.
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  GetForgeAppProperty200Response,
  MultiEntityResultAppProperty,
} from '../models/index';

export interface DeleteForgeAppPropertyRequest {
    propertyKey: string;
}

export interface GetForgeAppPropertiesRequest {
    cursor?: string;
    limit?: number;
}

export interface GetForgeAppPropertyRequest {
    propertyKey: string;
}

export interface PutForgeAppPropertyRequest {
    propertyKey: string;
    body: object;
}

/**
 * 
 */
export class AppPropertiesApi extends runtime.BaseAPI {

    /**
     * Creates request options for deleteForgeAppProperty without sending the request
     */
    async deleteForgeAppPropertyRequestOpts(requestParameters: DeleteForgeAppPropertyRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['propertyKey'] == null) {
            throw new runtime.RequiredError(
                'propertyKey',
                'Required parameter "propertyKey" was null or undefined when calling deleteForgeAppProperty().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("oAuthDefinitions", ["write:app-data:confluence"]);
        }


        let urlPath = `/app/properties/{propertyKey}`;
        urlPath = urlPath.replace(`{${"propertyKey"}}`, encodeURIComponent(String(requestParameters['propertyKey'])));

        return {
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Deletes a Forge app property. This API can only be accessed using **[asApp()](https://developer.atlassian.com/platform/forge/apis-reference/fetch-api-product.requestconfluence/#method-signature)** requests from Forge.
     * Deletes a Forge app property.
     */
    async deleteForgeAppPropertyRaw(requestParameters: DeleteForgeAppPropertyRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.deleteForgeAppPropertyRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Deletes a Forge app property. This API can only be accessed using **[asApp()](https://developer.atlassian.com/platform/forge/apis-reference/fetch-api-product.requestconfluence/#method-signature)** requests from Forge.
     * Deletes a Forge app property.
     */
    async deleteForgeAppProperty(requestParameters: DeleteForgeAppPropertyRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.deleteForgeAppPropertyRaw(requestParameters, initOverrides);
    }

    /**
     * Creates request options for getForgeAppProperties without sending the request
     */
    async getForgeAppPropertiesRequestOpts(requestParameters: GetForgeAppPropertiesRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        if (requestParameters['cursor'] != null) {
            queryParameters['cursor'] = requestParameters['cursor'];
        }

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("oAuthDefinitions", []);
        }


        let urlPath = `/app/properties`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Gets Forge app properties. This API can only be accessed using **[asApp()](https://developer.atlassian.com/platform/forge/apis-reference/fetch-api-product.requestconfluence/#method-signature)** requests from Forge.
     * Get Forge app properties.
     */
    async getForgeAppPropertiesRaw(requestParameters: GetForgeAppPropertiesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<MultiEntityResultAppProperty>> {
        const requestOptions = await this.getForgeAppPropertiesRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response);
    }

    /**
     * Gets Forge app properties. This API can only be accessed using **[asApp()](https://developer.atlassian.com/platform/forge/apis-reference/fetch-api-product.requestconfluence/#method-signature)** requests from Forge.
     * Get Forge app properties.
     */
    async getForgeAppProperties(requestParameters: GetForgeAppPropertiesRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<MultiEntityResultAppProperty> {
        const response = await this.getForgeAppPropertiesRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getForgeAppProperty without sending the request
     */
    async getForgeAppPropertyRequestOpts(requestParameters: GetForgeAppPropertyRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['propertyKey'] == null) {
            throw new runtime.RequiredError(
                'propertyKey',
                'Required parameter "propertyKey" was null or undefined when calling getForgeAppProperty().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("oAuthDefinitions", []);
        }


        let urlPath = `/app/properties/{propertyKey}`;
        urlPath = urlPath.replace(`{${"propertyKey"}}`, encodeURIComponent(String(requestParameters['propertyKey'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Gets a Forge app property by property key. This API can only be accessed using **[asApp()](https://developer.atlassian.com/platform/forge/apis-reference/fetch-api-product.requestconfluence/#method-signature)** requests from Forge.
     * Get a Forge app property by key.
     */
    async getForgeAppPropertyRaw(requestParameters: GetForgeAppPropertyRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GetForgeAppProperty200Response>> {
        const requestOptions = await this.getForgeAppPropertyRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response);
    }

    /**
     * Gets a Forge app property by property key. This API can only be accessed using **[asApp()](https://developer.atlassian.com/platform/forge/apis-reference/fetch-api-product.requestconfluence/#method-signature)** requests from Forge.
     * Get a Forge app property by key.
     */
    async getForgeAppProperty(requestParameters: GetForgeAppPropertyRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GetForgeAppProperty200Response> {
        const response = await this.getForgeAppPropertyRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for putForgeAppProperty without sending the request
     */
    async putForgeAppPropertyRequestOpts(requestParameters: PutForgeAppPropertyRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['propertyKey'] == null) {
            throw new runtime.RequiredError(
                'propertyKey',
                'Required parameter "propertyKey" was null or undefined when calling putForgeAppProperty().'
            );
        }

        if (requestParameters['body'] == null) {
            throw new runtime.RequiredError(
                'body',
                'Required parameter "body" was null or undefined when calling putForgeAppProperty().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("oAuthDefinitions", ["write:app-data:confluence"]);
        }


        let urlPath = `/app/properties/{propertyKey}`;
        urlPath = urlPath.replace(`{${"propertyKey"}}`, encodeURIComponent(String(requestParameters['propertyKey'])));

        return {
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters['body'] as any,
        };
    }

    /**
     * Creates or updates a Forge app property. This API can only be accessed using **[asApp()](https://developer.atlassian.com/platform/forge/apis-reference/fetch-api-product.requestconfluence/#method-signature)** requests from Forge.
     * Create or update a Forge app property.
     */
    async putForgeAppPropertyRaw(requestParameters: PutForgeAppPropertyRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.putForgeAppPropertyRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Creates or updates a Forge app property. This API can only be accessed using **[asApp()](https://developer.atlassian.com/platform/forge/apis-reference/fetch-api-product.requestconfluence/#method-signature)** requests from Forge.
     * Create or update a Forge app property.
     */
    async putForgeAppProperty(requestParameters: PutForgeAppPropertyRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.putForgeAppPropertyRaw(requestParameters, initOverrides);
    }

}
